#!/bin/bash
# shellcheck disable=SC2034,SC1090

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode disabled # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# shellcheck disable=SC1091
source "$ZSH/oh-my-zsh.sh"

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# shellcheck disable=SC2154
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
    export EDITOR="code --wait"
else
    export EDITOR="vim"
fi

HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST          # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY   # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY      # Share history between all sessions.
setopt HIST_FIND_NO_DUPS  # Do not display a line previously found.
setopt HIST_REDUCE_BLANKS # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY        # Don't execute immediately upon history expansion.

TIMEZONE=$(timedatectl show | grep Timezone= | awk -F= '{print $2}')
export TIMEZONE

IP_ADDRESS=$(hostname -I | tr " " "\n" | grep -v : | grep -v 172 | head -n1)
export IP_ADDRESS

export LC_COLLATE="C" # sort dotfiles first

# shellcheck disable=SC2155
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket) # for ssh auth

path+="$HOME/bin"
path+="$HOME/.local/bin"

if command -v mise >/dev/null; then
    eval "$(mise activate zsh)"
fi

# shellcheck disable=SC1091
# shellcheck disable=SC2154
source "$ZDOTDIR/.zsh_aliases"

# update zsh on chezmoi apply
chezmoi() {
    command chezmoi "$@"
    if [[ "$1" == "apply" ]]; then
        omz reload
    fi
}

# PROMPT
# shellcheck disable=SC1087,SC2154
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
# shellcheck disable=SC2016
PROMPT+=' %{$fg[cyan]%}%~%{$reset_color%} $(git_prompt_info)'
