#!/bin/bash

alias ls="ls --color=auto -a --classify --group-directories-first"
alias ll="ls --color=auto -lha --classify --group-directories-first"
alias fixup="git rebase -i HEAD~10 --autostash"
alias zshreload="omz reload"
alias telnet="telnet -e '^['" # i fucking hate telnet

# total vscode death
killvscode() {
    local pids
    pids=$(ps -e | awk '/[[:space:]]code-/{print $1}')
    [[ -n "$pids" ]] && echo "$pids" | xargs kill || echo "No VS Code processes found"
}
